In [1]:
import numpy as np
import copy

In [2]:
not_check_mate_t = np.array([[1,2,3,4,0,3,2,1],
                    [6,6,6,6,6,6,6,6],
                    [0,0,0,0,0,0,0,0],
                    [0,7,0,0,5,0,0,0],
                    [0,0,0,0,0,0,0,0],
                    [0,9,0,0,7,0,8,0],
                    [12,12,12,12,0,12,12,12],
                    [0,8,0,10,11,9,0,0]])

In [3]:
check_mate_t =  np.array([[1,2,3,4,0,3,2,1],
                    [6,6,6,6,6,6,6,6],
                    [0,0,0,0,0,0,0,0],
                    [0,7,0,0,5,0,12,0],
                    [0,0,0,0,0,0,0,0],
                    [0,9,0,0,7,0,8,0],
                    [12,12,12,12,0,12,12,12],
                    [0,8,0,10,11,9,0,0]])

In [4]:
initial_t = np.array([[1,2,3,4,5,3,2,1],
                    [6,6,6,6,6,6,6,6],
                    [0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0],
                    [12,12,12,12,12,12,12,12],
                    [7,8,9,10,11,9,8,7]])

In [5]:
def kings(t, side):
    k = 5 if side == "white" else 11
    pos = tuple(map(lambda x: x[0] if x.size >0 else -1, np.where(t == k)))
        
    if pos[0] < 0 or pos[0] < 0:
        return None
        
    return pos

In [6]:
np.where(initial_t == 22)

(array([], dtype=int64), array([], dtype=int64))

In [7]:
def is_check(t, side):
    res = False
    i = 0 if side == "white" else 1
    king = kings(t,side)
    #print(king)
    if king:
        if check_rook(t,king, side):
            #print("Check ",side," king by rook")
            res = True
        if check_knight(t, king, side):
            #print("Check ",side," king by knight")
            res = True
        if check_bishop(t, king, side):
            #print("Check ",side," king by bishop")
            res = True
        if check_queen(t, king, side):
            #print("Check ",side," king by queen")
            res = True
        if check_king(t, king, side):
            #print("Check ",side," king by king")
            res = True
        if check_pawn(t, king, side):
            #print("Check ",side," king by pawn")
            res = True
    else:
        res = True
    return res

In [8]:
def valid_pos(pos):
    return pos[0]>=0 and pos[1]>=0 and pos[0]<8 and pos[1]<8

In [9]:
def check_rook(t, king, side, k=None): #k=None util para calcular jaque de reina
    if not k:
        k = 7 if side == "white" else 1
    res = False
    for sq in t[king[0]+1:,king[1]]: # down
        if sq != 0:
            if sq == k:
                #print("down")
                res =  True
                break
    for sq in np.flip(t[:king[0],king[1]], 0): # up
        if sq != 0:
            if sq == k:
                #print("up")
                res =  True
                break
    for sq in t[king[0],king[1]+1:]: # right
        if sq != 0:
            if sq == k:
                #print("right")
                res =  True
                break
    for sq in np.flip(t[king[0],:king[1]], 0): # left
        if sq != 0:
            if sq == k:
                #print("left")
                res =  True
                break
                
    return res

In [10]:
def knight_moves_coor(pos):
    res = []
    for x in [-2,2]:
        for y in [-1,1]:
            if valid_pos((pos[0]+x, pos[1]+y)):
                res.append((pos[0]+x,pos[1]+y))
    for x in [-1,1]:
        for y in [-2,2]:
            if valid_pos((pos[0]+x, pos[1]+y)):
                res.append((pos[0]+x,pos[1]+y))
    return res
            

def check_knight(t, king, side):
    k = 9 if side == "white" else 3
    res = False
    for i,j in knight_moves_coor(king):
        sq = t[i,j]
        if sq == k:
            res = True
            break
    
    return res

In [11]:
def check_bishop(t, pos, side, k=None):
    if not k:
        k = 8 if side == "white" else 2 # 2 si se buscan blancas y 8 si se buscan negras
    res = False
    a = False
    b = False
    c = False
    d = False
    i = 1
    while(not a or not b or not c or not d):
        if not valid_pos((pos[0]+i, pos[1]+i)):
            a = True
        if not a and t[pos[0]+i,pos[1]+i] != 0:
            if t[pos[0]+i,pos[1]+i] == k:
                res = True
                break
            else:
                a = True
                
        if not valid_pos((pos[0]-i, pos[1]+i)):
            b = True
        if not b and t[pos[0]-i,pos[1]+i] != 0:
            if t[pos[0]-i,pos[1]+i] == k:
                res = True
                break
            else:
                b = True
                
        if not valid_pos((pos[0]-i, pos[1]-i)):
            c = True
        if not c and t[pos[0]-i,pos[1]-i] != 0:
            if t[pos[0]-i,pos[1]-i] == k:
                res = True
                break
            else:
                c = True
                
        if not valid_pos((pos[0]+i, pos[1]-i)):
            d = True
        if not d and t[pos[0]+1,pos[1]-i] != 0:
            if t[pos[0]+1,pos[1]-i] == k:
                res = True
                break
            else:
                d = True
        i += 1
        
    return res
            
            

In [12]:
def check_queen(t, pos, side):
    k = 10 if side == "white" else 4 # 4 si se buscan blancas y 10 si se buscan negras
    
    return check_rook(t,pos,side,k=k) or check_bishop(t,pos,side,k=k)

In [13]:
def check_king(t, pos, side):
    k = 11 if side == "white" else 5
    for x,y in [(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)]:
        if valid_pos((pos[0]+x, pos[1]+y)):
            if t[pos[0]+x, pos[1]+y] != 0:
                if t[pos[0]+x, pos[1]+y] == k:
                    return True
                
    return False

In [14]:
def check_pawn(t, pos, side):
    k = 12 if side == "white" else 6
    x = 1 if side == "white" else -1
    for y in [-1, 1]:
        if valid_pos((pos[0]+x,pos[1]+y)):
            if t[pos[0]+x,pos[1]+y] == k:
                return True
    return False

In [15]:
def rook_moves(t, pos):
    i,j = pos
    p = t[i,j]
    side = "white" if p < 7 else "black"
    res = []
    wd = [True,True,True,True]
    k = 1
    while(any(wd)):
        for w,(x,y) in enumerate([(i+k, j),(i-k, j),(i, j+k),(i, j-k)]):
            if wd[w] and valid_pos((x,y)) and (t[x,y] == 0 or (side == "white" and t[x,y] > 6) or (side == "black" and t[x,y] < 7)):
                if t[x,y] != 0:
                    wd[w] = False
                s = copy.copy(t)
                s[i,j] = 0
                s[x,y] = p
                res.append(s)
            else:
                wd[w] = False 
                    
        k += 1
        
    return res

In [16]:
def bishop_moves(t, pos):
    i,j = pos
    p = t[i,j]
    side = "white" if p < 7 else "black"
    res = []
    wd = [True,True,True,True]
    k = 1
    while(any(wd)):
        for w,(x,y) in enumerate([(i+k, j+k),(i-k, j+k),(i+k, j-k),(i-k, j-k)]):
            if wd[w] and valid_pos((x,y)) and (t[x,y] == 0 or (side == "white" and t[x,y] > 6) or (side == "black" and t[x,y] < 7)):
                if t[x,y] != 0:
                    wd[w] = False
                s = copy.copy(t)
                s[i,j] = 0
                s[x,y] = p
                res.append(s)
            else:
                wd[w] = False 
                    
        k += 1
        
    return res

In [17]:
def knight_moves(t, pos):
    i,j = pos
    p = t[i,j]
    side = "white" if p < 7 else "black"
    res = []
    for x,y in knight_moves_coor(pos):
        if t[x,y] == 0 or (side == "white" and t[x,y] > 6) or (side == "black" and t[x,y] < 7):
            s = copy.copy(t)
            s[i,j] = 0
            s[x,y] = p
            res.append(s)
            
    return res

In [18]:
def queen_moves(t,pos):
    res = []
    r_m = rook_moves(t,pos)
    if r_m: 
        res.append(r_m)
        
    b_m = bishop_moves(t,pos)
    if b_m: 
        res.append(b_m)
    return res

In [19]:
def king_moves(t,pos):
    res = []
    i,j = pos
    p = t[i,j]
    side = "white" if p < 7 else "black"
    for x,y in [(i-1,j-1),(i-1,j),(i-1,j+1),(i,j-1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)]:
        if valid_pos((x,y)):
            if t[x,y] == 0 or (side == "white" and t[x,y] > 6) or (side == "black" and t[x,y] < 7):
                s = copy.copy(t)
                s[i,j] = 0
                s[x,y] = p
                res.append(s)
    return res
            

In [20]:
def pawn_moves(t, pos):
    res = []
    i,j = pos
    p = t[i,j]
    side = "white" if p < 7 else "black"
    
    k = 1 if side == "white" else -1
    x = i + k
    
    if t[x, j] == 0:
        s = copy.copy(t)
        s[i,j] = 0
        s[x,j] = p
        res.append(s)

        if ((i == 1 and side == "white") or (i==6 and side == "black")) and t[x+k, j] == 0: # salida del peon
            s = copy.copy(t)
            s[i,j] = 0
            s[x+k,j] = p
            res.append(s)
        
    
    for y in [j-1, j+1]:
        if valid_pos((x,y)) and (t[x,y] != 0) and ((side == "white" and t[x,y] > 6) or (side == "black" and t[x,y] < 7)):
                s = copy.copy(t)
                s[i,j] = 0
                s[x,y] = p
                res.append(s)
    return res

In [21]:
switcher = {1:rook_moves, 2:bishop_moves, 3: knight_moves, 4: queen_moves, 5: king_moves, 6:pawn_moves}

def possible_moves(t, side):
    res = []
    k = 0 if side == "white" else 6
    for i in range(8):
        for j in range(8):
            sq = t[i,j]
            if sq != 0 and sq > k and sq < k+7:
                moves = switcher[(((sq-1)%6) + 1) ](t,(i,j))
                if moves:
                    res += moves
            
    return res

In [22]:
def is_check_mate(t, side):
    check = is_check(t, side)
    mate = True
    if check:
        for m in possible_moves(t,side):
            if not is_check(m, side):
                print(m)
                mate = False
                break
            #print(m)

    return check and mate

        

In [23]:
def check_mate(t):
    for side in ["white", "black"]:
        if is_check_mate(t, side):
            print("check mate", side, "king")
        else:
            print("not check mate for", side, "king")

        

In [29]:
check_mate(initial_t)

not check mate for white king
not check mate for black king


In [27]:
check_mate(check_mate_t)

check mate white king
not check mate for black king


In [28]:
check_mate(not_check_mate_t)

[[ 1  2  3  4  0  3  2  1]
 [ 6  6  6  6  6  6  6  6]
 [ 0  0  0  0  0  5  0  0]
 [ 0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  9  0  0  7  0  8  0]
 [12 12 12 12  0 12 12 12]
 [ 0  8  0 10 11  9  0  0]]
not check mate for white king
not check mate for black king
